spring:
  datasource:
    url: jdbc:h2:file:~/testdb0618
    username: scott
    password: tiger
  h2:
    console:
      enabled: true
logging:
  level:
    root: info
  com:
    cht:
      springboot:
        demo:
          Demo6JDBC: debug
